# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cbindC <- function(mf, Y) {
    .Call(`_batchCox_cbindC`, mf, Y)
}

matMultC <- function(aa, bb) {
    .Call(`_batchCox_matMultC`, aa, bb)
}

elementE <- function(x) {
    .Call(`_batchCox_elementE`, x)
}

nominatorC <- function(d, s) {
    .Call(`_batchCox_nominatorC`, d, s)
}

