// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// cbindC
NumericMatrix cbindC(NumericMatrix mf, NumericMatrix Y);
RcppExport SEXP _batchCox_cbindC(SEXP mfSEXP, SEXP YSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mf(mfSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Y(YSEXP);
    rcpp_result_gen = Rcpp::wrap(cbindC(mf, Y));
    return rcpp_result_gen;
END_RCPP
}
// matMultC
NumericVector matMultC(NumericMatrix aa, NumericVector bb);
RcppExport SEXP _batchCox_matMultC(SEXP aaSEXP, SEXP bbSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type aa(aaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bb(bbSEXP);
    rcpp_result_gen = Rcpp::wrap(matMultC(aa, bb));
    return rcpp_result_gen;
END_RCPP
}
// elementE
NumericVector elementE(NumericVector x);
RcppExport SEXP _batchCox_elementE(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(elementE(x));
    return rcpp_result_gen;
END_RCPP
}
// nominatorC
NumericMatrix nominatorC(NumericMatrix d, NumericVector s);
RcppExport SEXP _batchCox_nominatorC(SEXP dSEXP, SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type d(dSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type s(sSEXP);
    rcpp_result_gen = Rcpp::wrap(nominatorC(d, s));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_batchCox_cbindC", (DL_FUNC) &_batchCox_cbindC, 2},
    {"_batchCox_matMultC", (DL_FUNC) &_batchCox_matMultC, 2},
    {"_batchCox_elementE", (DL_FUNC) &_batchCox_elementE, 1},
    {"_batchCox_nominatorC", (DL_FUNC) &_batchCox_nominatorC, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_batchCox(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
